### ISSUE TITLE
Not compatible in java 17+ 

### ISSUE THREAD

**Issue by rahitashpaul** [h3110w0r1d-y/BurpLoaderKeygen#10]
![image](https://user-images.githubusercontent.com/67377363/149509822-e21da697-6374-4e7f-9c41-27dabd73c5bf.png)
![image](https://user-images.githubusercontent.com/67377363/149510112-5f5b245b-bca4-4d36-9ff8-3e7a476565a6.png)
Please make the red box editable that can be edited what command need to run this under java 17+
https://forum.portswigger.net/thread/run-burp-on-openjdk-17-5611cb564e50e

**Comment by 2891954521** [comment]
You can create a bat file and input this command. It works perfectly with burp, but it may need to be reactivated every once in a while.
```
@start javaw --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -javaagent:BurpLoaderKeygen.jar -noverify -jar burpsuite_pro_v2021.12.1.jar
```

**Comment by h3110w0r1d-y** [comment]
I have released a new version that adds support for Java 16 and 17

**Comment by rahitashpaul** [comment]
NICE Update
AWWWsome
BOOOS
