### ISSUE TITLE
Keygen not work 2024.2.1

### ISSUE THREAD

**Issue by tyloren0a** [h3110w0r1d-y/BurpLoaderKeygen#10]
Keygen not work 2024.2.1

**Comment by tyloren0a** [comment]
JDK 21 working. fixed.

**Comment by tyloren0a** [comment]
![Ekran görüntüsü 2024-03-01 174319](https://github.com/h3110w0r1d-y/BurpLoaderKeygen/assets/117740575/e574e364-3ed4-411b-9b15-4545aaa51f3d)

not fixed.

**Comment by tyloren0a** [comment]
I get this kind of error when I try to start it.

**Comment by h3110w0r1d-y** [comment]
<img width="798" alt="image" src="https://github.com/h3110w0r1d-y/BurpLoaderKeygen/assets/52311174/f3dab566-adfa-4939-b173-85b683a5b60e">

I cannot reproduce this issue

**Comment by tyloren0a** [comment]
Hi @h3110w0r1d-y ,
what version of java are you using? also what could be causing this problem? I am using JDK 21.
command : 
java "--add-opens=java.desktop/javax.swing=ALL-UNNAMED" "--add-opens=java.base/java.lang=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED" "-Dsun.java2d.d3d=false" "-javaagent:D:/burp/BurpLoaderKeygen_v1.17.jar" "-noverify" "-jar" "D:\burp\burpsuite_pro_v2024.2.1.jar"

**Comment by tyloren0a** [comment]
Hi @h3110w0r1d-y ,
keygen was not working because it was on drive D. It works fine on the C drive.
issue fixed.

**Comment by rafitamolin** [comment]
> Hi @h3110w0r1d-y , keygen was not working because it was on drive D. It works fine on the C drive. issue fixed.

I get this same error using Adoptium JDK 21 and I have Burp installed on my C: drive

![Ekran görüntüsü 2024-03-01 174319](https://private-user-images.githubusercontent.com/117740575/309295652-e574e364-3ed4-411b-9b15-4545aaa51f3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NTM3MTAsIm5iZiI6MTcwOTg1MzQxMCwicGF0aCI6Ii8xMTc3NDA1NzUvMzA5Mjk1NjUyLWU1NzRlMzY0LTNlZDQtNDExYi05YjE1LTQ1NDVhYWE1MWYzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QyMzE2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjU3NjY5Mjc3YTVmYjRhOTg4YjEwOGVlNzE5ZmUxOWY1OWM3OWU1MzFjOTBiMGIyMGE3OTE0MjIwZWJiYWZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hsPrV-bGJAh2jlDEe2JEFJ8RMJT2nbZYyZJGW3KcQMs)

I used to run Burp Suite with JDK 17, but with 2024.2.1.1 version it crashes instantly

Any ideas?

**Comment by tyloren0a** [comment]
> > Hi @h3110w0r1d-y , keygen was not working because it was on drive D. It works fine on the C drive. issue fixed.
> 
> I get this same error using Adoptium JDK 21 and I have Burp installed on my C: drive
> 
> ![Ekran görüntüsü 2024-03-01 174319](https://private-user-images.githubusercontent.com/117740575/309295652-e574e364-3ed4-411b-9b15-4545aaa51f3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NTM3MTAsIm5iZiI6MTcwOTg1MzQxMCwicGF0aCI6Ii8xMTc3NDA1NzUvMzA5Mjk1NjUyLWU1NzRlMzY0LTNlZDQtNDExYi05YjE1LTQ1NDVhYWE1MWYzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QyMzE2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjU3NjY5Mjc3YTVmYjRhOTg4YjEwOGVlNzE5ZmUxOWY1OWM3OWU1MzFjOTBiMGIyMGE3OTE0MjIwZWJiYWZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hsPrV-bGJAh2jlDEe2JEFJ8RMJT2nbZYyZJGW3KcQMs)
> 
> I used to run Burp Suite with JDK 17, but with 2024.2.1.1 version it crashes instantly
> 
> Any ideas?

create a folder on the desktop then move keygen and burp in the same folder. try launching from the folder on the desktop.

**Comment by nianhao** [comment]
I get the same error on JDK 21 & bp 2024.2.1.4，and when I change bp to 2024.1.16，the issue solved
