### ISSUE TITLE
以汉化模式启动后回车键失效

### ISSUE THREAD

**Issue by latxz2025** [h3110w0r1d-y/BurpLoaderKeygen#13]
汉化模式启动后，输入回车键变为\t，没有换行效果，而英文模式下是\r\n。
以下是截图：
![Snipaste_2022-03-13_18-55-17](https://user-images.githubusercontent.com/52594948/158056375-cbbb2c92-e7e7-4829-a5c7-ef64a9186b08.jpg)
![Snipaste_2022-03-13_18-56-07](https://user-images.githubusercontent.com/52594948/158056380-fda285d5-6bd6-438f-82f3-50e52f519ece.jpg)

**Comment by h3110w0r1d-y** [comment]
之前只是整合了一下别人写的，有一些BUG，但是我太菜了不会修，汉化也没多大必要，于是把汉化功能去掉了，可以试一下这位大佬写的修复版 https://github.com/WankkoRee/BurpLoaderKeygenCnF

**Comment by latxz2025** [comment]
嗯，那个版本的没有问题了。
