### ISSUE TITLE
macos激活不了么？

### ISSUE THREAD

**Issue by wms1899** [h3110w0r1d-y/BurpLoaderKeygen#14]
macos上会弹出这样一个对话框，激活不了啊？
![20240521233843](https://github.com/h3110w0r1d-y/BurpLoaderKeygen/assets/35290685/73961f77-a78b-446d-bac7-9fb38a5ae32a)

**Comment by h3110w0r1d-y** [comment]
https://github.com/h3110w0r1d-y/BurpLoaderKeygen/blob/main/how-to-use.md

按照链接中的方法操作

**Comment by mrmign** [comment]
burp_pro_2024.5.3 同样激活不了呢

**Comment by grofis** [comment]
第一次无法激活，第二次下载安装就是直接要输key了。输入key根本没用，结论就是方法失效了。

**Comment by h3110w0r1d-y** [comment]
> 第一次无法激活，第二次下载安装就是直接要输key了。输入key根本没用，结论就是方法失效了。

![QQ_1723356784120](https://github.com/user-attachments/assets/bff41be3-5901-4544-a2b4-1645696fd686)

![QQ_1723356801106](https://github.com/user-attachments/assets/d56e96b2-0486-464e-a5eb-5a3d76aa684b)
