### ISSUE TITLE
kali

### ISSUE THREAD

**Issue by surpassoneself** [h3110w0r1d-y/BurpLoaderKeygen#17]
您好，当前jar包适用于kali系统的linux么？

**Comment by googleweb** [comment]
kali里默认安装的是社区版，你可以单独下载专业版使用。如果也想使用菜单的话，burp菜单调用的是一个脚本命令，你可以自己修改

sudo vi /usr/bin/burpsuite

**Comment by surpassoneself** [comment]
十分感谢您的指导，希望能和您学习更多的知识。





工作源于生活，美好的生活基于努力的工作
手机：13665419820
 
From: googleweb
Date: 2022-08-01 16:54
To: h3110w0r1d-y/BurpLoaderKeygen
CC: surpassoneself; Author
Subject: Re: [h3110w0r1d-y/BurpLoaderKeygen] kali (Issue #17)
kali里默认安装的是社区版，你可以单独下载专业版使用。如果也想使用菜单的话，burp菜单调用的是一个脚本命令，你可以自己修改
sudo vi /usr/bin/burpsuite

**Comment by googleweb** [comment]
我已经收到您的信件!
