### ISSUE TITLE
"The supplied key was not recognized" error while trying to activate Burpsuite using loader. Doesn't work with older versions too.

### ISSUE THREAD

**Issue by iamprabhu0** [h3110w0r1d-y/BurpLoaderKeygen#17]

**Comment by imnuke** [comment]
Hello, i have the same problem, how did you solved that?

**Comment by xoity** [comment]
having same problem did u find a solution?

**Comment by iamprabhu0** [comment]
I know you already read this [guide](https://github.com/h3110w0r1d-y/BurpLoaderKeygen/blob/main/how-to-use.md) but following the file structure as it is without any extra sub folders worked for me
