### ISSUE TITLE
无法激活 大佬救救

### ISSUE THREAD

**Issue by kkAct** [h3110w0r1d-y/BurpLoaderKeygen#19]
环境：
openjdk11
mac m1 pro
burpsuite_pro_macos_arm64_v2022_8_1

<img width="1368" alt="截屏2022-08-17 00 53 10" src="https://user-images.githubusercontent.com/41529707/184936121-cb93bbfd-7423-4f04-b093-61ff0ad335a7.png">

**Comment by kiiiiiingdom** [comment]
那你这就属于完全没用过了.. 
点[这个](https://www.youtube.com/watch?v=e9u6myyve4g)油管视频看看吧

**Comment by h3110w0r1d-y** [comment]
请使用刚刚发布的1.6版本，使用方法见README.md中Mac版使用方法
