### ISSUE TITLE
mac bigSur 11.4 使用崩溃

### ISSUE THREAD

**Issue by Tasfa** [h3110w0r1d-y/BurpLoaderKeygen#2]
注册使用后崩溃

**Comment by h3110w0r1d-y** [comment]
请问你的jdk版本多少，在什么地方崩溃，可以说的详细点吗。
我在mac上测试过，相同版本的系统，可以正常使用的。
检查一下你的jdk版本，在终端中直接执行`java -javaagent:BurpLoaderKeygen.jar -noverify -jar burpsuite_pro.jar`看看有什么报错
