### ISSUE TITLE
激活失败

### ISSUE THREAD

**Issue by S-TUSK** [h3110w0r1d-y/BurpLoaderKeygen#20]
运行闪退了一下后没反应

**Comment by h3110w0r1d-y** [comment]
请问Java版本多少，什么操作系统，控制台手动执行命令，报错截图

**Comment by S-TUSK** [comment]
![3SDDFKU6NGKLH{A 9HA_38F](https://user-images.githubusercontent.com/108928321/185744071-b0dd0d15-ac0a-4cef-a35d-10654d97afff.png)
大佬看一下，操作系统win10，双击和cmd运行都会闪退

**Comment by h3110w0r1d-y** [comment]
cmd运行的报错截图

**Comment by S-TUSK** [comment]
没有报错，运行显示启动界面后瞬间闪退，用的最新版的burp

**Comment by h3110w0r1d-y** [comment]
Java版本太低，最新版的Burp不支持java8

**Comment by h3110w0r1d-y** [comment]
换更高版本的java或者将高版本的java环境放到同目录下，注册机自动调用
![image](https://user-images.githubusercontent.com/52311174/185744315-f449aefd-498a-4526-9adc-55ca5c91989f.png)
