### ISSUE TITLE
汉化启动无法双击打开

### ISSUE THREAD

**Issue by winnower-sliff** [h3110w0r1d-y/BurpLoaderKeygen#21]
之前用了大佬您的原版能够正常使用，最近想加汉化于是就又来找您下载CN版，但是双击.jar文件却无法打开启动界面，请问有什么办法吗？

**Comment by h3110w0r1d-y** [comment]
汉化功能已经去掉了，不维护了，使用这位大佬开发的吧 https://github.com/WankkoRee/BurpLoaderKeygenCnF

**Comment by winnower-sliff** [comment]
谢谢！！没想到这么快就回复了，太感谢了！
