### ISSUE TITLE
Please Help My BrupLoaderKeygen Problem

### ISSUE THREAD

**Issue by rahitashpaul** [h3110w0r1d-y/BurpLoaderKeygen#23]
I downloaded "BurpLoaderKeygen" & "Burp Suite Professional".
First run BurpLoaderKeygen take the key and pasting the key into the "Enter License Key"  dialog box but not take me the next.
 I try it many times but I fail.

Help Me
Thanks

**Comment by h3110w0r1d-y** [comment]
https://github.com/h3110w0r1d-y/BurpLoaderKeygen/issues/22
Only v2022.8 and below is supported, for v2022.9 and above, please use ja-netfilter.
