### ISSUE TITLE
最新版本 2022.11 失效

### ISSUE THREAD

**Issue by Asura88** [h3110w0r1d-y/BurpLoaderKeygen#24]
最新版本 2022.11 失效

**Comment by jhhd88** [comment]
+1

**Comment by wanswu** [comment]
> 最新版本 2022.11 失效

又找到了方法

**Comment by tyloren0a** [comment]
> > 最新版本 2022.11 失效
> 
> 又找到了方法

这条路是什么？

**Comment by Asura88** [comment]
https://github.com/googleweb/loader/releases



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月8日(周二) 晚上9:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [h3110w0r1d-y/BurpLoaderKeygen] 最新版本 2022.11 失效 (Issue #24)




   
最新版本 2022.11 失效
  
又找到了方法
  
这条路是什么？

**Comment by h3110w0r1d-y** [comment]
https://github.com/h3110w0r1d-y/BurpLoaderKeygen/releases/tag/1.8

**Comment by tyloren0a** [comment]
> https://github.com/h3110w0r1d-y/BurpLoaderKeygen/releases/tag/1.8

不幸的是，这并不奏效。

**Comment by tyloren0a** [comment]
Hi Not work @h3110w0r1d-y

**Comment by h3110w0r1d-y** [comment]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/52311174/200699216-898fbfb0-2261-4963-b654-9ae6edf80b36.png">
@tyloren0a Please provide your system, burp, java version

**Comment by h3110w0r1d-y** [comment]
> Hi, Not work @h3110w0r1d-y

@tyloren0a https://github.com/h3110w0r1d-y/BurpLoaderKeygen/issues/25#issuecomment-1308277016
