### ISSUE TITLE
java16及以上版本破解失败

### ISSUE THREAD

**Issue by lucksec** [h3110w0r1d-y/BurpLoaderKeygen#25]
是不是得清楚之前版本破解信息

**Comment by h3110w0r1d-y** [comment]
刚刚测了下，Java16及以上版本失效了，Mac版自带的是Java17

**Comment by Tukali** [comment]
> 刚刚测了下，Java16及以上版本失效了，Mac版自带的是Java17，换成Java16以下就可以正常用

那是不是不能直接app打开了，我这边用loader打开正常破解，app打开就没用，好像app自动调用自带java

**Comment by googleweb** [comment]
![屏幕截图 2022-11-09 124951](https://user-images.githubusercontent.com/11829793/200741507-35646863-0860-4b70-9002-1167a2a3d849.png)

jdk19可以运行。估计其他版本的loader的启动参数在高版本的java中失效了吧。

**Comment by Q1ngShan** [comment]
是可以激活的应该是参数问题，启动loader后终端执行启动burp
`
"/Applications/Burp Suite Professional.app/Contents/Resources/jre.bundle/Contents/Home/bin/java" -javaagent:BurpLoaderKeygen.jar --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED -jar burpsuite_pro.jar
`
按正常步骤激活，vmoptions中同样添加以下内容即可
`
-javaagent:BurpLoaderKeygen.jar
-noverify
--add-opens=java.desktop/javax.swing=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED
--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED 
--add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED

`

**Comment by h3110w0r1d-y** [comment]
@Q1ngShan 感谢，已在Keygen中增加缺少的参数

**Comment by tyloren0a** [comment]
> -javaagent:BurpLoaderKeygen.jar --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED -jar burpsuite_pro.jar

是否有可能使这个许可证不受限制？ @h3110w0r1d-y  我看到一些许可证上写着 "过期10000"。

**Comment by h3110w0r1d-y** [comment]
> > -javaagent:BurpLoaderKeygen.jar --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED -jar burpsuite_pro.jar
> 
> 是否有可能使这个许可证不受限制？ @h3110w0r1d-y 我看到一些许可证上写着 "过期10000"。

证书里有一个毫秒时间戳，指的是许可证的过期时间，修改这个时间戳即可
![image](https://user-images.githubusercontent.com/52311174/200823965-f93c6653-4257-4c4c-9879-fc3605a3de66.png)

**Comment by tyloren0a** [comment]
> > > -javaagent:BurpLoaderKeygen.jar --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED -jar burpsuite_pro.jar
> > 
> > 
> > 是否有可能使这个许可证不受限制？ @h3110w0r1d-y 我看到一些许可证上写着 "过期10000"。
> 
> 证书里有一个毫秒时间戳，指的是许可证的过期时间，修改这个时间戳即可 ![image](https://user-images.githubusercontent.com/52311174/200823965-f93c6653-4257-4c4c-9879-fc3605a3de66.png)

谢谢你告诉我这个，但我不知道怎么做，所以你们能做到吗？ 你能更新密钥吗？

**Comment by tyloren0a** [comment]
> > > > -javaagent:BurpLoaderKeygen.jar --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED -jar burpsuite_pro.jar
> > > 
> > > 
> > > 是否有可能使这个许可证不受限制？ @h3110w0r1d-y 我看到一些许可证上写着 "过期10000"。
> > 
> > 
> > 证书里有一个毫秒时间戳，指的是许可证的过期时间，修改这个时间戳即可 ![image](https://user-images.githubusercontent.com/52311174/200823965-f93c6653-4257-4c4c-9879-fc3605a3de66.png)
> 
> 谢谢你告诉我这个，但我不知道怎么做，所以你们能做到吗？ 你能更新密钥吗？

@h3110w0r1d-y

**Comment by Hus3ar** [comment]
2022.11.1的burp，在windows jdk18的情况下还是无法注册

**Comment by h3110w0r1d-y** [comment]
@Hus3ar 在我电脑上测试没有问题
![image](https://user-images.githubusercontent.com/52311174/202447986-0026c224-2f69-4e1f-8c9a-70d5512b5b29.png)
