### ISSUE TITLE
burpbounty pro agent

### ISSUE THREAD

**Issue by murray-sky** [h3110w0r1d-y/BurpLoaderKeygen#27]
师傅能添加burpbounty pro的agent吗，在gogleweb(https://github.com/googleweb/loader)里面有这个的agent代码

**Comment by h3110w0r1d-y** [comment]
https://github.com/h3110w0r1d-y/BurpLoaderKeygen/releases/tag/1.12

**Comment by wzqs** [comment]
大佬 有 burpbounty pro 的下载地址吗？

**Comment by h3110w0r1d-y** [comment]
https://burpbounty.net/burp-bounty-pro-v2-6-0/

**Comment by wzqs** [comment]
> https://burpbounty.net/burp-bounty-pro-v2-6-0/

https://burpbounty.net/wp-content/uploads/2023/01/BurpBountyPro_v2.6.1.zip

感谢
