### ISSUE TITLE
对最新版burp suite已失效

### ISSUE THREAD

**Issue by PACHAKUTlQ** [h3110w0r1d-y/BurpLoaderKeygen#28]
burp版本：burpsuite_pro_v2022.12.4
os：win10
java：jdk-19.0.1
key复制进去后bp一直显示认不出key，不管是直接双击burploaderkeygen还是用cmd（javaw --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -jar -Xmx1G -javaagent:BurpLoaderKeygen.jar -noverify -jar burpsuite_pro_v2022.12.4.jar）都不行。
如果不只有我遇到这个问题的话，那可能是burp的新版改进校验机制了。希望大佬能破解。谢谢

**Comment by h3110w0r1d-y** [comment]
<img width="789" alt="image" src="https://user-images.githubusercontent.com/52311174/208293351-8a57def6-5aa9-48a1-b451-7432a1a2a9d9.png">

**Comment by PACHAKUTlQ** [comment]
谢谢。确实，我试了一下，现在是可以的（也许是因为我是jdk19，但是keygenerator扫出来的是另一个目录的jdk16，我改了一下jdk16的文件夹的名字）。对不起，麻烦了。另外提个小建议：现在的keygenerator检查到不是最新版本之后，点击下载非常缓慢，可以换成官网上的下载链接：https://portswigger-cdn.net/burp/releases/download?product=pro&version=2022.12.4&type=WindowsX64，速度非常快

**Comment by h3110w0r1d-y** [comment]
好的，感谢提醒
