### ISSUE TITLE
好像没法用了

### ISSUE THREAD

**Issue by JiunnTarn** [h3110w0r1d-y/BurpLoaderKeygen#29]
大佬，好像没法用了

![image](https://user-images.githubusercontent.com/45126705/209958126-4a3ab68e-46a8-4b6d-b596-bef5d94cbbc2.png)

附上我的版本信息
> Keygen: v1.11
> Burp Suite: v2022.3.6 (v2022.12.3, v2022.12.4, v2022.12.5 也没法用）

望解答，谢谢！

**Comment by h3110w0r1d-y** [comment]
![image](https://user-images.githubusercontent.com/52311174/209960236-194667f8-95cd-4aea-959a-0d1bd4d6f45d.png)

**Comment by JiunnTarn** [comment]
抱歉我搞错了，我点了联网激活😂，谢谢大佬！
