### ISSUE TITLE
i need you , baby

### ISSUE THREAD

**Issue by Huuuuuaaaa** [h3110w0r1d-y/BurpLoaderKeygen#3]
根据二○○二年一月一日《计算机软件保护条例》第十七条规定：为了学习和研究软件内含的设计思想和原理，通过安装、显示、传输或者存储软件等方式使用软件的，可以不经软件著作权人许可，不向其支付报酬!

**Comment by ALEX-X36** [comment]
拜托，Burp是国外的，而且这是对软件的破解，但没了确实心疼

**Comment by kaiser20106** [comment]
> 拜托，Burp是国外的，而且这是对软件的破解，但没了确实心疼

在中国不就应该根据中国的法律吗？
