### ISSUE TITLE
选择汉化后出现bug

### ISSUE THREAD

**Issue by FallBacktoTogether** [h3110w0r1d-y/BurpLoaderKeygen#3]
版本：jdk-11.0.12，jar为官网下载未改名
加载汉化之后，抓包把数据放到攻击器会出现以下情况：
1、burpsuite_pro_v2021.7.2.jar：数据直接乱码
2、burpsuite_pro_v2021.8.jar：数据正常，但是点击开始使用攻击器的时候会提示，The basic request does not contain a blank line, and so is not a valid HTTP request.
上面两种情况撤掉汉化之后恢复正常

**Comment by h3110w0r1d-y** [comment]
这个是汉化的BUG，原作者的就有（在readme最下面说明了，https://github.com/funkyoummp/BurpSuiteCn ）
本人菜狗，不会修，只是把功能给整合了一下😢

**Comment by FallBacktoTogether** [comment]
![05819758](https://user-images.githubusercontent.com/80873500/128461365-c260e276-241f-4a75-97ef-bae148477bed.png)

**Comment by WankkoRee** [comment]
可能可以尝试一下我的修复版本，希望对你有用：[WankkoRee/BurpLoaderKeygenCnF](https://github.com/WankkoRee/BurpLoaderKeygenCnF)

**Comment by imortall** [comment]
汉化后使用 重发时修改数据没办法换行

**Comment by Anclhe** [comment]
> 汉化后使用 重发时修改数据没办法换行

我也是遇到了这个情况，不会修
