### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by cmunaro** [h3110w0r1d-y/BurpLoaderKeygen#30]
If this is for education, where is the source code?

**Comment by h3110w0r1d-y** [comment]
Use jd-gui please

**Comment by cmunaro** [comment]
If we decompile the program with jd-gui we can't have the source code, but only a reinterpretation of the bytecode..
What should we learn from this repo besides from a simple way to use a paid software for free?
If instead the would be also the source code that we can understand, comment and evolve could find this useful to expand our knowledge
