### ISSUE TITLE
Burploader not work burpsuite 2023.1

### ISSUE THREAD

**Issue by Druyaj018** [h3110w0r1d-y/BurpLoaderKeygen#31]
Hi,
Burploader not work burpsuite 2023.1

**Comment by Lkhsss** [comment]
雀氏，在使用burpsuite 2023.1时，不会让你人工验证，直接显示不识别

**Comment by h3110w0r1d-y** [comment]
https://github.com/h3110w0r1d-y/BurpLoaderKeygen/releases/tag/1.12
