### ISSUE TITLE
与chrome的冲突

### ISSUE THREAD

**Issue by windmoxa** [h3110w0r1d-y/BurpLoaderKeygen#32]
配置好burpsuite过后替换了原来的启动方式(方法就像链接里的一样:https://blog.csdn.net/m0_46135508/article/details/107006128),在安装chrome前一切正常，一旦安装chrome并且打开过一次chrome过后直接失效,重启后打开burpsuite只有burploaderkeygen的界面并且无法运行burpsuite,求大佬告知问题所在
两个版本分别是BurpLoaderKeygen1.11和BurpSuite pro 2022.12.5

**Comment by h3110w0r1d-y** [comment]
看一下控制台里的报错

**Comment by windmoxa** [comment]
> 看一下控制台里的报错

一旦安装chrome过后就会像图里一样报错,然后就再也打不开了

![20230117230154](https://user-images.githubusercontent.com/109521949/212934788-661e7e21-f141-4fd9-a040-ac705c4faa9b.png)


看起来就像路径有问题一样

**Comment by h3110w0r1d-y** [comment]
手动运行一下那个命令看看报什么错
<img width="980" alt="image" src="https://user-images.githubusercontent.com/52311174/213154053-db04b01d-14c4-4d78-90aa-b99596232df1.png">

**Comment by windmoxa** [comment]
> 手动运行一下那个命令看看报什么错 <img alt="image" width="980" src="https://user-images.githubusercontent.com/52311174/213154053-db04b01d-14c4-4d78-90aa-b99596232df1.png">
显然这个东西脱离了我能理解的范畴

![20230119102609](https://user-images.githubusercontent.com/109521949/213341176-540bae66-e953-47f9-996e-0474e5e6a9a8.png)

报错:
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Error opening zip file or JAR manifest missing : BurpLoaderKeygen.jar
Error occurred during initialization of VM
agent library failed to init: instrument

**Comment by h3110w0r1d-y** [comment]
https://github.com/h3110w0r1d-y/BurpLoaderKeygen/releases/tag/1.13

**Comment by h3110w0r1d-y** [comment]
把 BurpLoaderKeygen.jar和burpsuite_pro_20xx.x.jar放到相同目录下，比如/opt/burpsuite/下，把/usr/bin/burpsuite内容改成
```
/usr/lib/jvm/java-17-openjdk-amd64/bin/java -jar /opt/burpsuite/burploaderkeygen.jar
```

**Comment by windmoxa** [comment]
> /usr/lib/jvm/java-17-openjdk-amd64/bin/java -jar /opt/burpsuite/burploaderkeygen.jar

感谢帮助，以及可以共存了
![QQ截图20230119144157](https://user-images.githubusercontent.com/109521949/213373839-bcdaaf51-25b9-48f7-bb28-5c037eb59ce7.png)

**Comment by Mycroft-Hu** [comment]
1.13在Windows下无法启动BP Jar包，会闪过启动界面

**Comment by h3110w0r1d-y** [comment]
> 1.13在Windows下无法启动BP Jar包，会闪过启动界面

@Mycroft-Hu 是不是Java版本太低了？最新版burp需要使用Java17

**Comment by Mycroft-Hu** [comment]
> > 1.13在Windows下无法启动BP Jar包，会闪过启动界面
> 
> @Mycroft-Hu 是不是Java版本太低了？最新版burp需要使用Java17

不会，我是17.0.5的JDK，在Loader 1.12的时候是没问题的

**Comment by h3110w0r1d-y** [comment]
@Mycroft-Hu 麻烦在终端手动执行一下注册机中的命令，截图输出报错
<img width="638" alt="image" src="https://user-images.githubusercontent.com/52311174/215297884-a37dfff4-3ac5-487e-a77e-2c43ecd0cd46.png">

**Comment by Mycroft-Hu** [comment]
> @Mycroft-Hu 麻烦在终端手动执行一下注册机中的命令，截图输出报错 <img alt="image" width="638" src="https://user-images.githubusercontent.com/52311174/215297884-a37dfff4-3ac5-487e-a77e-2c43ecd0cd46.png">

@h3110w0r1d-y 知道原因了，这个版本的loader在命令行中对文件夹的空格添加了“%20”
"C:\Program Files\Java\jdk-17.0.5\bin\java.exe" "--add-opens=java.desktop/javax.swing=ALL-UNNAMED" "--add-opens=java.base/java.lang=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED" "-javaagent:E:/Applications/Penetration%20Testing/Burp%20Suite%20Professional/Burp%20Suite%20Professional%202022.12.6/BurpLoaderKeygen.jar" "-noverify" "-jar" "E:\Applications\Penetration Testing\Burp Suite Professional\Burp Suite Professional 2022.12.6\burpsuite_pro_v2022.12.7.jar" 

但奇怪的是前面有%20后面没有，去掉后就能正常启动了

**Comment by h3110w0r1d-y** [comment]
@Mycroft-Hu 已修复 https://github.com/h3110w0r1d-y/BurpLoaderKeygen/releases/tag/1.14
