### ISSUE TITLE
BurpBountyPro 无法激活

### ISSUE THREAD

**Issue by murray-sky** [h3110w0r1d-y/BurpLoaderKeygen#33]
我用的是mac版的burp，配置了vmoptions.txt，能够激活burp，但是填入任意BurpBountyPro的license key之后点击activate无法激活，前面的scanner和profile都是灰色的，然后license status是disable状态

**Comment by h3110w0r1d-y** [comment]
什么都不用输入，直接点Activate就可以呀

**Comment by murray-sky** [comment]
> 什么都不用输入，直接点Activate就可以呀

我直接点击Activate也不行，用的是最新版https://burpbounty.net/wp-content/uploads/2023/01/BurpBountyPro_v2.6.1.zip

**Comment by murray-sky** [comment]
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/80733736/215299094-e48ca28e-5ba7-431f-81e1-b625e051c840.png">
点击Activate后这个界面还是这样的

**Comment by h3110w0r1d-y** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/52311174/215299097-abb5ad9e-a553-4500-9789-1dc9a1627fe8.png">
<img width="986" alt="image" src="https://user-images.githubusercontent.com/52311174/215299107-f573cb20-c77d-4f21-a19e-0fe555763ac8.png">
我也是用的2.6.1，没啥问题🤔

**Comment by murray-sky** [comment]
会不会是环境有问题，我找人试试

**Comment by murray-sky** [comment]
可以了，我找了下原因，以前我用的破解版需要屏蔽hosts文件，现在我把hosts文件给改了，就能激活了，谢谢师傅了
