### ISSUE TITLE
How to remove older license file from mac?

### ISSUE THREAD

**Issue by AkshayraviC09YC47** [h3110w0r1d-y/BurpLoaderKeygen#37]
Hello @h3110w0r1d-y 

How to remove old license from mac and do fresh installation for burp crack? on which path the license file is located?

**Comment by AkshayraviC09YC47** [comment]
<img width="822" alt="image" src="https://user-images.githubusercontent.com/58636452/227724063-bd806e58-98f6-4730-bac0-8bd2fda6243a.png">


Tried with this also and ended up with this issue

**Comment by niuTT** [comment]
同问

**Comment by h3110w0r1d-y** [comment]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/52311174/231660728-a30fc26b-f78d-4943-bd91-c5b42c6e229d.png">

**Comment by AkshayraviC09YC47** [comment]
Thanks for the help

**Comment by AkshayraviC09YC47** [comment]
Thanks for the help
