### ISSUE TITLE
Auto选项关闭

### ISSUE THREAD

**Issue by A1debaran** [h3110w0r1d-y/BurpLoaderKeygen#38]
- 系统: Win
- Java版本: 11

注册机auto的选项如何关闭？

**Comment by h3110w0r1d-y** [comment]
注册机目录下，有一个`.config.ini`，删除即可
<img width="421" alt="image" src="https://user-images.githubusercontent.com/52311174/231712541-663c4594-0966-43c4-a030-1ce9d8f4797e.png">

**Comment by A1debaran** [comment]
> 
十分感谢！

**Comment by h3110w0r1d-y** [comment]
现在还可以通过 `java -jar burploaderkeygen.jar -auto 0` 命令关闭
