### ISSUE TITLE
功能要求 (Feature request)

### ISSUE THREAD

**Issue by Divinemonk** [h3110w0r1d-y/BurpLoaderKeygen#40]
# 用中文（表达     (In Chinese)

我真的很喜欢你的工具！
（我是用谷歌翻译翻译的，所以如果有拼写错误请理解）

我写了一个简单的 [指南](https://github.com/Divinemonk/burpsuite_pro) 来使用这个工具，结合最好的资源让它工作！

我想创建一个工具来自动执行手动下载和运行该工具的过程。

这是一种“功能请求”，您可以添加命令行参数吗？所以当我运行你的代码时，我不必担心 UI/gui。例如 `java -jar BurpLoaderKeygen.jar -a -n <name to register>` 其中 `-a` 用于 `Auto run`。

希望你尽快添加它 |谢谢 ：）

# In English    (用英语)

I really liked you're tool!
(I'm translating using google translate, so if any misspells please understand)

I have written a simple [guide](https://github.com/Divinemonk/burpsuite_pro) to use the tool, combining best resources to make it working!

I want to create a  tool that automates the process of downloading and running the tool manuallly.

This is sort of `feature request`, can you add command line arguments. So when i'm running you're code I don't have to worry about UI/gui. example `java -jar BurpLoaderKeygen.jar -a -n <name to register>` where `-a` is for `Auto run`.

Hope you add it soon | Thankyou :)

**Comment by h3110w0r1d-y** [comment]
https://github.com/h3110w0r1d-y/BurpLoaderKeygen/releases/tag/1.15

**Comment by Divinemonk** [comment]
# 用中文（表达 (In Chinese)
您好，感谢您如此迅速地添加该功能！

新更新添加了用户名、自动运行和忽略，但仍然运行 GUI！就像当我们运行我制作的脚本时（下载 [此处](https://github.com/Divinemonk/burpsuite_pro/releases/latest/download/burpsuite_pro.sh) 并运行 `sh burpsuite_pro.sh` ）它会加载一切正常但当我们运行它时，它打开了 gui 而不是直接运行并打开 burp.

您能否在没有 gui 的情况下自动执行该过程！
希望你尽快添加它 |谢谢 ：）

# In English (用英语)
Hello, thank you for adding the feature so quickly!

The new update adds username, auto run and ignore but stills run the GUI! Like when we run the script I made (download [here](https://github.com/Divinemonk/burpsuite_pro/releases/latest/download/burpsuite_pro.sh) and run `sh burpsuite_pro.sh` ) it dwonloads everything fine but when we run it, but it opens gui instead of directly running and opening burp.

Can you please automate the process, without gui!
Hope you add it soon | Thankyou :)

**Comment by h3110w0r1d-y** [comment]
My mistake，fixed😅, please download again https://github.com/h3110w0r1d-y/BurpLoaderKeygen/releases/tag/1.15

**Comment by Divinemonk** [comment]
Thankyou - that works smooth :)
(https://github.com/Divinemonk/burpsuite_pro)
