### ISSUE TITLE
建议检测最新稳定版不包括早期测试版

### ISSUE THREAD

**Issue by 9th0top** [h3110w0r1d-y/BurpLoaderKeygen#44]
burp版本 https://portswigger.net/burp/releases/data
获取最新稳定版本号 releaseChannels=Stable

下载最新稳定版
https://portswigger-cdn.net/burp/releases/download?product=pro&version=2023.6.2&type=Jar

**Comment by h3110w0r1d-y** [comment]
https://github.com/h3110w0r1d-y/BurpLoaderKeygen/releases/tag/1.16

**Comment by 9th0top** [comment]
非常感谢，大佬好快的速度，能直接发布jdk8编译的release吗，用着方便一点

**Comment by h3110w0r1d-y** [comment]
> 非常感谢，大佬好快的速度，能直接发布jdk8编译的release吗，用着方便一点

一直都是使用Java8编译的

<img width="404" alt="image" src="https://github.com/h3110w0r1d-y/BurpLoaderKeygen/assets/52311174/ce8826a9-7415-4299-99d7-493a2bf498d0">

**Comment by h3110w0r1d-y** [comment]
目前Burp已经不支持Java8了，但是这个注册机是可以使用Java8启动的，你可以把高版本的Java环境放到同目录下的jdk/jre文件夹中，注册机会自动检查并调用高版本的Java环境启动Burp

**Comment by 9th0top** [comment]
![image](https://github.com/h3110w0r1d-y/BurpLoaderKeygen/assets/127181925/58bc50a9-5f54-4c45-9375-888680c521e4)
找到原因了，1.16版本无法加载启动命令。
应该是判定jdk版本时，先取的环境变量path的jdk版本，而不是先判断的./bin/java版本，
建议启动burp的jdk版本的优先级应该是./bin/java，然后是path里的jdk版本

**Comment by 9th0top** [comment]
![image](https://github.com/h3110w0r1d-y/BurpLoaderKeygen/assets/127181925/33742918-4970-4df8-bc40-6a96e0984091)

java环境

**Comment by h3110w0r1d-y** [comment]
非常抱歉，因为时间有限，上午写完没怎么测试就发布了😅，现已修复

https://github.com/h3110w0r1d-y/BurpLoaderKeygen/releases/tag/v1.17

**Comment by h3110w0r1d-y** [comment]
<img width="1196" alt="image" src="https://github.com/h3110w0r1d-y/BurpLoaderKeygen/assets/52311174/761fb13b-e429-4643-8f81-258c033c8cd6">
