### ISSUE TITLE
为什么我的一直提示重新输入密钥

### ISSUE THREAD

**Issue by xxghk** [h3110w0r1d-y/BurpLoaderKeygen#5]
![20210922_020235](https://user-images.githubusercontent.com/49458169/134223922-08f98af0-b37a-4f5c-9cb6-9e4b886d7bdc.jpg)

**Comment by xxghk** [comment]
提示：无法识别提供的许可证密钥，请重新输入许可证密钥

**Comment by cokyrain** [comment]
不要用java17

**Comment by xxghk** [comment]
> 不要用java17

难道是java17的问题？
