### ISSUE TITLE
Java Runtime only recognizes class file versions up to 60.0

### ISSUE THREAD

**Issue by canyesilyurt** [h3110w0r1d-y/BurpLoaderKeygen#7]
Error: LinkageError occurred while loading main class burp.StartBurp
	java.lang.UnsupportedClassVersionError: burp/StartBurp has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
<img width="952" alt="image" src="https://github.com/h3110w0r1d-y/BurpLoaderKeygen/assets/36952967/f8b14f79-74da-484e-8e8f-c98f003528e6">

**Comment by h3110w0r1d-y** [comment]
Please upgrade your Java

**Comment by canyesilyurt** [comment]
> Please upgrade your Java

I installed the java library using brew. Can you send me the updated java link?

**Comment by h3110w0r1d-y** [comment]
install Java 17

**Comment by canyesilyurt** [comment]
I downloaded the latest version from the official Java site. 

<img width="466" alt="image" src="https://github.com/h3110w0r1d-y/BurpLoaderKeygen/assets/36952967/e00b3fc1-7891-4adb-bffc-8a07289d6d24">

**Comment by canyesilyurt** [comment]
<img width="498" alt="image" src="https://github.com/h3110w0r1d-y/BurpLoaderKeygen/assets/36952967/79a66243-66f5-4fd2-8818-0051bfd55a5a">
and I downloaded and installed the java 17 kit you said but the version update still didn't happen

**Comment by canyesilyurt** [comment]
<img width="748" alt="image" src="https://github.com/h3110w0r1d-y/BurpLoaderKeygen/assets/36952967/99875966-f26b-47da-90a3-a5e1cda57de9">

**Comment by ImYasine** [comment]
Have you resolved it?

**Comment by canyesilyurt** [comment]
> Have you resolved it?

I couldn't solve it, I bought the program.

**Comment by h3110w0r1d-y** [comment]
> <img alt="image" width="748" src="https://private-user-images.githubusercontent.com/36952967/301495197-99875966-f26b-47da-90a3-a5e1cda57de9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMTk3MjgsIm5iZiI6MTcxODAxOTQyOCwicGF0aCI6Ii8zNjk1Mjk2Ny8zMDE0OTUxOTctOTk4NzU5NjYtZjI2Yi00N2RhLTkwYTMtYTVlMWNkYTU3ZGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDExMzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNmExZTQxOTQ1YmFjOGM2ODliYmY0NzRmMzBmNzhjNWZlNTE0OTMyZTU0NGJlOGVhZjZmODFiMjQ2ZDgzZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V2wlM3yYgLLEKnHe-K8nzdmlSkOy92vQrKx2LV74ktQ">

In your screenshot, the version of Java used is 16.

**Comment by h3110w0r1d-y** [comment]
Please use the correct version of Java to run Burp. Here is a comparison table of Java versions and class file versions::


| Java Version | Class File Version |
|--------------|--------------------|
|     8.0      |        52.0        |
|     9.0      |        53.0        |
|    10.0      |        54.0        |
|    11.0      |        55.0        |
|    12.0      |        56.0        |
|    13.0      |        57.0        |
|    14.0      |        58.0        |
|    15.0      |        59.0        |
|    16.0      |        60.0        |
|    17.0      |        61.0        |
|    18.0      |        62.0        |
|    19.0      |        63.0        |
|    20.0      |        64.0        |


[Usage](https://github.com/h3110w0r1d-y/BurpLoaderKeygen/blob/main/how-to-use.md)

**Comment by ImYasine** [comment]
Yes that's how i resolved that so thought to tell you i was facing the same issue and deleted my Java versions and installed new version and after that it worked
